config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/about", to: "pages#about"
  get "/contact", to: "pages#contact"
  resources :posts
  get "/blog", to: "posts#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :photo
  has_rich_text :body

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  helper ActionText::Engine.helpers

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :about, :contact ]

  def home
    @last_post = Post.last
    @other_posts = Post.where.not(id: @last_post.id)
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @last_post = Post.last
    @other_posts = Post.where.not(id: @last_post.id)
  end

  def show
    @similar_posts = Post.where.not(id: @post.id).limit(3)
  end

  def new
    redirect_to root_path unless current_user
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    redirect_to root_path unless current_user
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to blog_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :highlight, :body, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="wrapper">
      <%= render "shared/navbar_admin" if current_user %>
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/_about_mobile.html.erb
<!-- MOBILE -->
<div class="d-sm-none">
  <div class="d-flex d-sm-none justify-content-around mx-5 mb-3">
    <button class="btn btn-default btn-yellow" type="button" data-bs-toggle="collapse" data-bs-target="#professionally" aria-expanded="false" aria-controls="collapseExample">
      PROFESSIONALLY
    </button>
  </div>
  <div class="collapse" id="professionally">
    <div class="card card-body">
      <div class="professionally">
        <div class="section">
          <div class="stroked">
            <%= image_tag "brush.svg", class: "stroke" %>
            <p class="section-title text-center over-stroke about">I'm an engineer</p>
          </div>
          <p>I started coding in summer 2018 after quitting my corporate career of 4 years in product and marketing.</p>
          <p>Since then I worked as a <strong>Fullstack Developer</strong> with various technologies, the main ones being <strong>Ruby on Rails</strong>, <strong>React Native</strong> and <strong>Python</strong>.</p>
          <p>In the meantime I also upskilled myself in <strong>Data Science</strong> and worked with Data Analysis, Machine Learning and Data Engineering. Despite I’m stunned by the possibilies of this field, I’m still a classic dev at heart 😉</p>
          <p>As far as engineering goes, I also have good genes thanks to my family. If you need any help with fixing anything at home or with your car - hit me up!</p>
        </div>
        <div class="section">
          <div class="stroked">
            <%= image_tag "brush.svg", class: "stroke yellow" %>
            <p class="section-title text-center over-stroke about">I'm a manager</p>
          </div>
          <p>University degree doesn’t make you a professional however thanks to my management studies I was more or less ready to the on the challenge.</p>
          <p>Over the last couple of years in the tech world I have been an Engineering Manager and managed big sized teaching teams that were working for our bootcamps. Big sized - around 30 people on irregular schedule with varying experience from very junior assistant to experts with years of experience.</p>
        </div>
        <div class="section">
          <div class="stroked">
            <%= image_tag "brush.svg", class: "stroke mint" %>
            <p class="section-title text-center over-stroke about">I'm a teacher</p>
          </div>
          <p>Teaching was always a part of my everyday life, starting from educating <strong>sales teams</strong> and <strong>clients</strong> about the specifics of activewear, through <strong>coding classes</strong> for big sized groups up to 50 people, <strong>1:1 mentoring</strong> and last but not least - <strong>training dogs</strong>.</p>
          <p>I personally believe that teaching should be exclusive to people who enjoy it, ideally love it. Without your own passion and faith in your students it's very unlikely for them to get better and keep up the motivation to grow. For me being a teacher is a passion in itself - I love seeing people think, progress, fail and get up again for another round. There are only a few more satisfying things out there than this.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex d-sm-none justify-content-around mx-5 my-3">
    <button class="btn btn-default btn-yellow" type="button" data-bs-toggle="collapse" data-bs-target="#in-life" aria-expanded="false" aria-controls="collapseExample">
      IN LIFE
    </button>
  </div>
  <div class="collapse" id="in-life">
    <div class="card card-body">
      <div class="in-life">
        <div class="section">
          <p class="section-title text-center over-stroke about">I travel</p>
          <div class="centered">
            <%= image_tag "travel", height: 200, class: "d-block text-center m-2" %>
          </div>
          <p>Long story short - we have a campervan. Her name is Bine (reach out for more details behind its story 😉).</p>
          <p>This car has given a new quality to our travels - you can reach so many more places, meet more incredible people, wake up to the most beautiful views and be spontaneous on everyday basis.</p>
          <p>When we don’t drive, it means we have our backpacks full and are going somewhere far. Discovering other cultures, getting involved in local communities and spending stupid amounts of money on food are things we excel at.</p>
        </div>
        <div class="section">
          <p class="section-title text-center over-stroke about">I have a weakness for dogs</p>
          <div class="d-flex">
            <%= image_tag "dog", height: 200, class: "d-block text-center my-2 shadow-none" %>
            <p class='mt-3 mx-2'>I was growing up surrounded by them, from the moment I was born, until I left home for university. This setup created a very fundamental need to be around animals.</p>
          </div>
          <div>
            <p>Our four-legged friends can teach us more than we realize. In fact, they shape who we are in everyday life - as friends, coworkers, parents, strangers on the streets. We have recently adopted Leon, who you can see on the picture, and since day one we have started looking at the world in a different way.</p>
          </div>
        <div class="section">
          <p class="section-title text-center over-stroke about">I move</p>
          <div>
            <p>Don't trust the stereotype of a programmer. They don't only sit in front of the screen in their vintage sweaters. They also work from their beds in a reclined position.</p>
            <p>Ok, no more sarcasm. Personally I love movement and literally cannot spend my full days in front of the screen. If I ever tell you that I don't have any energy, tell me to get my ass up and move a little!</p>
            <%= image_tag "muaythai", height: 160, class: "d-block text-center my-3 shadow-none mx-auto" %>
            <p>How to move? I don't have a favorite. It can be a walk with Leon, heavy functional training session, a game of spike ball (which I'm horrible at) or a chilled yoga with Adriene (if you don't know her, highly recommend!)</p>
          </div>
        </div>
        <div class="section">
          <p class="section-title text-center over-stroke about">I write</p>
          <div>
            <p>Take it seriosuly or not (maybe better) but I've been an avid diarist and journalist for many years now.</p>
            <p>This doesn't make me a professional writer of any sort, but I can say proudly that I write. If you go to the <%= link_to "> blog <", blog_path, class: 'link' %> you can maybe find something for yourself there.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/_home_get_to_know_mobile.html.erb
<div class="d-block d-sm-none">
  <%= render "shared/get_to_know", mobile: true %>
</div>

app/views/pages/_home_posts_carousel_mobile.html.erb
<div class="d-block d-sm-none">
  <p class="section-title">READING</p>
  <div id="carouselExampleCaptions" class="carousel" data-bs-ride="false">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= render "shared/carousel_post", post: @last_post %>
      </div>
      <% if other_posts %>
        <% other_posts.limit(2).each do |post| %>
          <div class="carousel-item">
            <%= render "shared/carousel_post", post: post %>
          </div>
        <% end %>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

app/views/pages/about.html.erb
<div class="container">
  <p class="text-center about-slogan">and this page is about me</p>
  <div class="about-tldr">
    <div class="row">
      <div class="col-sm-4 p-0">
        <div class="about-image"></div>
      </div>
      <div class="col-sm-8">
        <div class="tldr-content">
          <p class="title">Simply, TL;DR</p>
          <div class="bullets mt-5">
            <div class="d-flex justify-content-start align-items-center mb-3">
              <%= image_tag "ellipse_orange", class:"bullet" %>
              <p class="mb-0">based in Berlin</p>
            </div>
            <div class="d-flex justify-content-start align-items-center mb-3">
              <%= image_tag "ellipse_yellow", class:"bullet" %>
              <p class="mb-0">driven by making a difference, teaching and mentoring others</p>
            </div>
            <div class="d-flex justify-content-start align-items-center mb-3">
              <%= image_tag "ellipse_green", class:"bullet" %>
              <p class="mb-0">software engineer, manager and teacher</p>
            </div>
            <div class="d-flex justify-content-start align-items-center mb-3">
              <%= image_tag "ellipse_orange", class:"bullet" %>
              <p class="mb-0">learned how to take care of her curly hair after 30 years of age</p>
            </div>
            <div class="d-flex justify-content-start align-items-center mb-3">
              <%= image_tag "ellipse_yellow", class:"bullet" %>
              <p class="mb-0">favorite food: oats, in any form</p>
            </div>
            <div class="d-flex justify-content-start align-items-center mb-3">
              <%= image_tag "ellipse_green", class:"bullet" %>
              <p class="mb-0">loves: travel, animals, movement</p>
            </div>
            <div class="d-flex justify-content-start align-items-center mb-3">
              <%= image_tag "ellipse_orange", class:"bullet" %>
              <p class="mb-0">speaks: english, german, polish</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <p class="more-info">If you have more time to get to know what I do:</p>
  <div class="row d-none d-sm-flex">
    <div class="col-6">
      <p class="section-title text-center">PROFESSIONALLY</p>
        <div class="professionally p-3">
          <div class="section mx-4">
            <div class="stroked">
              <%= image_tag "brush.svg", class: "stroke" %>
              <p class="section-title text-center over-stroke about">I'm an engineer</p>
            </div>
            <p>I started coding in summer 2018 after quitting my corporate career of 4 years in product and marketing.</p>
            <p>Since then I worked as a <strong>Fullstack Developer</strong> with various technologies, the main ones being <strong>Ruby on Rails</strong>, <strong>React Native</strong> and <strong>Python</strong>.</p>
            <p>In the meantime I also upskilled myself in <strong>Data Science</strong> and worked with Data Analysis, Machine Learning and Data Engineering. Although I’m stunned by the possibilies of this field, I’m still a classic dev at heart 😉</p>
            <p>As far as engineering goes, I also have good genes thanks to my family. If you need any help with fixing anything at home or with your car - hit me up!</p>
          </div>
          <div class="section mx-4">
            <div class="stroked">
              <%= image_tag "brush.svg", class: "stroke yellow" %>
              <p class="section-title text-center over-stroke about">I'm a manager</p>
            </div>
            <p>University degree doesn’t make you a professional however thanks to my management studies I was more or less ready to take on the challenge.</p>
            <p>Over the last couple of years I have been an <strong>Engineering Manager</strong> and <strong>managed big sized teaching teams</strong> that were working for coding bootcamps. Big sized meaning around 30 people on irregular schedule with varying experience ranging from junior assistants to experts with years of experience.</p>
          </div>
          <div class="section mx-4">
            <div class="stroked">
              <%= image_tag "brush.svg", class: "stroke mint" %>
              <p class="section-title text-center over-stroke about">I'm a teacher</p>
            </div>
            <p>Teaching was always a part of my everyday life, starting from educating <strong>sales teams</strong> and <strong>clients</strong> about the specifics of activewear, through <strong>coding classes</strong> for big sized groups up to 50 people, <strong>1:1 mentoring</strong> and last but not least - <strong>training dogs</strong>.</p>
            <p>I personally believe that teaching should be exclusive to people who enjoy it, ideally love it. Without your own passion and faith in your students it's very unlikely for them to get better and keep up the motivation to grow. For me being a teacher is a passion in itself - I love seeing people think, progress, fail and get up again for another round. There are only a few more satisfying things out there than this.</p>
          </div>
        </div>
    </div>
    <div class="col-6">
      <p class="section-title text-center">IN LIFE</p>
        <div class="in-life">
          <div class="section mx-4">
            <p class="section-title text-center over-stroke about">I travel</p>
            <div class="centered">
              <%= image_tag "travel", height: 200, class: "d-block text-center m-2" %>
            </div>
            <p>Long story short - we have a campervan. Her name is Bine (reach out for more details behind its story 😉).</p>
            <p>This car has given a new quality to our travels - you can reach so many more places, meet incredible people, wake up to the most beautiful views and be spontaneous on everyday basis.</p>
            <p>When we don’t drive, it means we have our backpacks full and are going somewhere far. Discovering other cultures, getting involved in local communities and spending stupid amounts of money on food are things we excel at.</p>
          </div>
          <div class="section mx-4">
            <p class="section-title text-center over-stroke about">I have a weakness for dogs</p>
            <div class="d-flex">
              <%= image_tag "dog", height: 340, class: "d-block text-center m-2 shadow-none" %>
              <div>
                <p>I was growing up surrounded by them, from the moment I was born, until I left home for university. This setup created a very fundamental need to be around animals.</p>
                <p>Our four-legged friends can teach us more than we realize. In fact, they shape who we are in everyday life - as friends, coworkers, parents, strangers on the streets. We have recently adopted Leon, who you can see on the picture, and since day one we have started looking at the world in a different way.</p>
              </div>
            </div>
          <div class="section mx-4">
            <p class="section-title text-center over-stroke about">I move</p>
            <div>
              <p>Don't trust the stereotype of a programmer. They don't only sit in front of the screen in their vintage sweaters. They also work from their beds in a reclined position.</p>
              <p>Ok, no more sarcasm. Personally I love movement and literally cannot spend my full days in front of the screen. If I ever tell you that I don't have any energy, tell me to get my ass up and move a little!</p>
              <%= image_tag "muaythai", height: 200, class: "d-block text-center my-3 shadow-none mx-auto" %>
              <p>How to move? I don't have a favorite. It can be a walk with Leon, heavy functional training session, a game of spike ball (which I'm horrible at) or a chilled yoga with Adriene (if you don't know her, highly recommend!)</p>

            </div>
          </div>
          <div class="section mx-4">
            <p class="section-title text-center over-stroke about">I write</p>
            <div>
              <p>Take it seriosuly or not (maybe better) but I've been an avid diarist and journalist for many years now.</p>
              <p>This doesn't make me a professional writer of any sort, but I can say proudly that I write. If you go to the <%= link_to "> blog <", blog_path, class: 'link' %> you can maybe find something for yourself there.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<%= render "about_mobile" %>
</div>

app/views/pages/contact.html.erb
<div class="container">
  <p class="text-center contact-slogan">Want to grab a coffee, collaborate or simply connect?</p>
  <p class="contact-reach text-center">Then reach out via one of:</p>
  <div class="d-flex justify-content-around align-items-center contact-icons">
    <%= link_to "https://www.linkedin.com/in/zuza-%C5%BCuber-a627b69a/", target: :blank, class: "contact-icon" do %>
      <i class="fa-brands fa-linkedin"></i>
    <% end %>
        <%= link_to "https://twitter.com/zzuziak_", target: :blank, class: "contact-icon" do %>
      <i class="fa-brands fa-twitter"></i>
    <% end %>
    <%= mail_to "zuberzuzanna@gmail.com", class: "contact-icon" do %>
      <i class="fa-solid fa-envelope"></i>
    <% end %>
    <%= link_to "https://www.github.com/zzuziak", target: :blank, class: "contact-icon" do %>
      <i class="fa-brands fa-github"></i>
    <% end %>
    <%= link_to "https://www.instagram.com/susan.naah/", target: :blank, class: "contact-icon" do %>
      <i class="fa-brands fa-instagram"></i>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <%= simple_form_for(@post) do |f| %>
    <%= f.input :title %>
    <%= f.input :highlight %>
    <%= f.rich_text_area :body, class: "form-control" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/posts/index.html.erb
<p class="text-center about-slogan">and this is some of my writing</p>

<%= render "shared/main_post_preview", post: @last_post if @last_post %>

<div class="row d-none d-sm-flex px-5">
  <div class="d-flex justify-content-around">
    <p class='blog-category'>WORK</p>
    <p class='blog-category'>TECH</p>
    <p class='blog-category'>TRAVEL</p>
    <p class='blog-category'>BOOKS</p>
    <p class='blog-category'>LIFE HACKS</p>
    <p class='blog-category'>DOGS</p>
    <p class='blog-category'>BERLIN</p>
  </div>
</div>

<div class="container d-none d-sm-block">
  <div class="row">
    <% @other_posts.each do |post| %>
      <% next if post.nil? %>
        <div class="col-4">
          <%= render "shared/post_preview", post: post, small: true %>
        </div>
    <% end %>
  </div>
</div>

<div class="d-sm-none">
  <% @other_posts.each do |post| %>
    <% next if post.nil? %>
    <%= render "shared/main_post_preview", post: post %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <%= simple_form_for(@post) do |f| %>
    <%= f.input :title %>
    <%= f.input :highlight %>
    <%= f.rich_text_area :body, class: "form-control" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="d-flex flex-column align-items-center">
    <% if current_user %>
      <div class="d-flex">
        <%= link_to "EDIT", edit_post_path(@post), class: "admin-nav-link" %>
        <%= link_to "DELETE", post_path(@post), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "admin-nav-link" %>
      </div>
    <% end %>
    <h1 class="post-title-show"><%= @post.title.upcase %></h1>
    <p class="post-highlight-show"><%= @post.highlight %></p>
    <%= cl_image_tag @post.photo&.key, class: 'post-image-show', crop: :fill %>
  </div>
  <div class="row mx-sm-3">
    <div class="col-12 col-sm-7">
      <p class="post-body-show"><%= @post.body %></p>
    </div>
    <div class="col-sm-1"></div>
    <div class="col-12 col-sm-4">
      <% if @similar_posts.any? %>
        <div class="similar-posts">
          <div>
            <div class="posts-header">
              <div class="stroked">
                <%= image_tag "brush.svg", class: "stroke" %>
                <p class="section-title-small text-center over-stroke">IF YOU LIKED THIS...</p>
              </div>
            </div>
            <div>
              <% @similar_posts.each do |post| %>
                <%= render 'shared/post_preview_xs', post: post %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_carousel_post.html.erb
<div class="d-flex justify-content-center align-items-center">
  <img src="<%= cl_image_path post.photo&.key %>" class="d-block w-100 carousel-image" alt="...">
</div>
<div class="d-flex w-100 justify-content-center">
  <%= link_to post_path(post), class: "link" do %>
    <p class="carousel-title"><span><%= post.title %></span></p>
  <% end %>
</div>

app/views/shared/_get_to_know.html.erb
<div class="<%= "mobile" if mobile %> col-sm-4 get-to-know mx-auto">
  <div class="stroked d-none d-sm-grid">
    <%= image_tag "brush.svg", class: "stroke" %>
    <p class="section-title text-center over-stroke">GET TO KNOW ME</p>
  </div>
  <div class="who-am-i">
    <p class="section-title d-sm-none">WHO AM I?</p>
    <div class="bullets mh-3">
      <div class="d-flex justify-content-start align-items-center mb-3">
        <%= image_tag "ellipse_orange", class:"bullet" %>
        <p class="mb-0">My name is Zuza Zuber. Polish girl living in Berlin.</p>
      </div>
      <div class="d-flex justify-content-start align-items-center mb-3">
        <%= image_tag "ellipse_yellow", class:"bullet" %>
        <p class="mb-0">I am a developer, manager, teacher, mentor, dog mum, campervan owner, movement lover.</p>
      </div>
      <div class="d-flex justify-content-start align-items-center mb-3">
        <%= image_tag "ellipse_green", class:"bullet" %>
        <p class="mb-0">I love helping people change their lives. I love making a difference for the planet and working on meaningful projects. I love people, just in general.</p>
      </div>
      <div class="d-flex justify-content-end">
        <%= link_to "Read more >", about_path, class: "more-link" %>
      </div>
    </div>
  </div>
  <div class="stroked d-none d-sm-grid">
    <%= image_tag "brush.svg", class: "stroke" %>
    <p class="section-title text-center over-stroke">LET'S COLLABORATE</p>
  </div>
  <p class="section-title d-sm-none mt-4">LET'S COLLABORATE</p>
  <p class="mx-3">If you are creating or working on something wholesome - reach out! I’m more than happy to volunteer, brainstorm, give advice, teach or collaborate on bigger projects.</p>
  <div class="d-flex justify-content-end">
    <%= link_to "Get in touch >", contact_path, class: "more-link mb-3" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-own">
  <div class="w-100 d-flex justify-content-between align-iterms-center">
    <ul class="navbar-nav d-none d-sm-flex">
        <li class="nav-item active">
          <%= link_to "HOME", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "BLOG", blog_path, class: "nav-link" %>
        </li>
        <!--<li class="nav-item">
          <%= link_to "MENTORING", "#", class: "nav-link" %>
        </li> -->
    </ul>
    <h1 class="title">Hi, I'm Zuz</h1>
    <ul class="navbar-nav right d-none d-sm-flex">
        <li class="nav-item left">
          <%= link_to "ABOUT ME", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "CONTACT", contact_path, class: "nav-link" %>
        </li>
    </ul>
    <li class="nav-item dropdown burger d-sm-none">
      <i class="fa-solid fa-bars" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <%=  %>
        <a class="dropdown-item" href="/">HOME</a>
        <a class="dropdown-item" href="/blog">BLOG</a>
        <a class="dropdown-item" href="/about">ABOUT ME</a>
        <a class="dropdown-item" href="/contact">CONTACT</a>
      </div>
    </li>
  </div>
</div>

app/views/shared/_navbar_admin.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-own">
  <div class="w-100 d-flex justify-content-end align-items-center">
    <ul class="navbar-nav right d-none d-sm-flex justify-content-end">
        <li class="nav-item left">
          <%= link_to "NEW POST", new_post_path, class: "admin-nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "LOG OUT", destroy_user_session_path, class: "admin-nav-link" %>
        </li>
    </ul>
  </div>
</div>